## Tensor Tutorial 

In [1]:
!pip install torch 
!pip install numpy

You should consider upgrading via the 'C:\Users\mibenama\OneDrive - Capgemini\Documents\PyTorch\pytorch_env\Scripts\python.exe -m pip install --upgrade pip' command.


You should consider upgrading via the 'C:\Users\mibenama\OneDrive - Capgemini\Documents\PyTorch\pytorch_env\Scripts\python.exe -m pip install --upgrade pip' command.


In [2]:
import torch 
import numpy as np 

In [3]:
#Directly from data
#Tensors can be created directly from data. The data type is automatically inferred
data = [[1,2], [3,4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [ ]:
#From a NumPy array
#Tensors can be created from NumPy arrays
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)



tensor([[1, 2],
        [3, 4]])


In [6]:
#From another tensor:
#The new tensor retains the properties (shape, datatype) of the argument tensor, unless explicitly overridden.

x_ones = torch.ones_like(x_data)
print(f"Ones Tensor : \n {x_ones}\n")

x_rand = torch.rand_like(x_data, dtype= torch.float)
print(f"Random Tensor: \n {x_rand}\n")

Ones Tensor : 
 tensor([[1, 1],
        [1, 1]])

Random Tensor: 
 tensor([[0.5631, 0.4536],
        [0.0665, 0.5206]])



In [9]:

#With random or constant values:
"shape is a tuple of tensor dimensions. In the functions below, it determines the dimensionality of the output tensor."

shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.5472, 0.2257, 0.8977],
        [0.2175, 0.8816, 0.6551]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
#Attributes of a Tensor
#Tensor attributes describe their shape, datatype, and the device on which they are stored.

tensor = torch.rand(3,4)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device is stored on: {tensor.device} ")


Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device is stored on: cpu 


In [10]:
#Operations on Tensors 
#Standard numpy-like indexing and slicing:

tensor = torch.ones(4,4)
print('tensor:', tensor)
print('First row: ',tensor[0])
print('First column: ',tensor[:,0])
print('Last column:', tensor[...,-1])
tensor[:,1]=0
print(tensor)

tensor: tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [ ]:
# torch.cat to concatenate a sequence of tensors along a given dimension 
#dim =1 nbr of columns changes
tensor_1 = torch.cat([tensor, tensor, tensor], dim=1)
print(tensor_1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [ ]:
#dim =0 number of rows changes 
t2 = torch.cat([tensor, tensor, tensor], dim=0)
print(t2)
print(t2.shape)  # Output: torch.Size([15, 3])

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
torch.Size([12, 4])


In [15]:
#torch.stack()
#Concatenates a sequence of tensors along a new dimension.
x = torch.randn(2,3)
torch.stack((x,x))

tensor([[[-0.0548,  0.0669, -1.7058],
         [ 0.3525, -1.0870,  0.9472]],

        [[-0.0548,  0.0669, -1.7058],
         [ 0.3525, -1.0870,  0.9472]]])

In [ ]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
y1 = tensor @ tensor.T # in pytorch @ stands for multiplication 

y2 = tensor.matmul(tensor.T) # in pytorch matmul stands for matric multiplication 
print("y2 = ",y2)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)


tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
y1 =  tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
y2 =  tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


In [20]:
# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
print(z1)
z2 = tensor.mul(tensor)
print(z2)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)



tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [22]:
#Single-element tensors If you have a one-element tensor,
agg = tensor.sum()
print(agg)
 
agg_item = agg.item()
print("agg_item = , type_agg_item = ",agg_item, type(agg_item) )

tensor(12.)
agg_item = , type_agg_item =  12.0 <class 'float'>


In [25]:
#In place operations 
#Operations that store the result into the operand are called in-place. They are denoted by a _ suffix. 
print(tensor, "\n")
tensor.add_(5)
#print(tensor)

y = torch.rand(2,3,)
print("y = ", y)
x = x.copy_(y)
print("x = ", x )

tensor([[11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.]]) 

y =  tensor([[0.8767, 0.2680, 0.6568],
        [0.1722, 0.6164, 0.2621]])
x =  tensor([[0.8767, 0.2680, 0.6568],
        [0.1722, 0.6164, 0.2621]])


In [26]:
#Tensor to Numpy array
t = torch.ones(5)
print(f"t : {t}")
n = t.numpy()
print(f"n:{n}")

t : tensor([1., 1., 1., 1., 1.])
n:[1. 1. 1. 1. 1.]


In [27]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]
